### ISSUE TITLE
Message that is broadcast to clients in a channel is being clipped

### ISSUE THREAD

**Issue by rodsmade** [0xEDU/ft_irc#17]
If I send this message in a channel:

`PRIVMSG #canal quem     eh      voce `

The clients in the channel (broadcast list) will receive only:

`:guillermo!~primeiratentativa@* PRIVMSG #canal :quem`

**Comment by 0xEDU** [comment]
Isn't this the expected response? Without the `:` before `quem     eh      voce ` it should just consider the first part of the message, `quem`.
