### ISSUE TITLE
Substitute `fcntl` for `write`

### ISSUE THREAD

**Issue by rodsmade** [0xEDU/ft_irc#22]
Apparently the pdf allows `fcntl` only for development in MacOS, which I believe is not the case for us.

**Comment by rodsmade** [comment]
Although I myself am actually developing in MacOS so maybe if we change it now the server might not work properly for me 🫠

**Comment by rodsmade** [comment]
@0xEDU's solution:

```
int sockfd = socket(AF_INET, SOCK_STREAM | SOCK_NONBLOCK, 0);
if (sockfd == -1) {
    // Handle the error
}
```

**Comment by 0xEDU** [comment]
Decided to keep it as is!
