### ISSUE TITLE
Server segfaults on `PRIVMSG` with no other parameters 

### ISSUE THREAD

**Issue by rodsmade** [0xEDU/ft_irc#27]
<img width="991" alt="Screenshot 2023-10-13 at 07 46 32" src="https://github.com/0xEDU/ft_irc/assets/49699403/e300089b-ca80-493e-95a3-8d6859146a1b">

**Comment by 0xEDU** [comment]
Adittionaly, PRIVMSG segfaults in various situations due to missing verifications
