### ISSUE TITLE
Finish JOIN command

### ISSUE THREAD

**Issue by 0xEDU** [0xEDU/ft_irc#4]
Acording to [IRC reference](https://datatracker.ietf.org/doc/html/rfc1459#section-4.2.1), we need to add:

- [x] Enter a channel using a key
- [x] Enter multiple channels, where some have keys and some don't (Ex:  JOIN #foo,#bar fubar,foobar     // join channel #foo using key "fubar" and channel #bar using key "foobar".)

**Comment by rodsmade** [comment]
Closed by #21
