### ISSUE TITLE
Is there a macro for that?

### ISSUE THREAD

**Issue by rodsmade** [0xEDU/ft_irc#5]
re: maximum port number. might vary per architecture?

https://github.com/0xEDU/ft_irc/blob/28b0cec4a09b4fd9425eef63109ccacbeefce553/srcs/classes/Server.cpp#L14

**Comment by Guiribei** [comment]
I'll close this issue once it was solved on commit b6b3c1d32f443a6cb25900ba63aef57e175ef544
