### ISSUE TITLE
Refactor: make it a MACRO in header?

### ISSUE THREAD

**Issue by rodsmade** [0xEDU/ft_irc#6]
https://github.com/0xEDU/ft_irc/blob/28b0cec4a09b4fd9425eef63109ccacbeefce553/srcs/classes/Server.cpp#L20C23-L20C23

**Comment by Guiribei** [comment]
Once we need the address of the variable to use later on, we must keep it the way it is.

**Comment by Guiribei** [comment]
Once we need the address of the variable to use later on, we must keep it the way it is.
